export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const ADD_QUANTITY_ITEM = "ADD_QUANTITY_ITEM";
export const SHOW_ALL_ITEM = "SHOW_ALL_ITEM";
export const DECREASE_QUANTITY_ITEM = "DECREASE_QUANTITY_ITEM";
export const SUMMARY_ITEM = "SUMMARY_ITEM";
export const CLEAR_ITEMS = "CLEAR_ITEMS";



